[32m2025-07-03 00:25:02 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - 495550 - LOGS_CAPTURED - Started capturing logs in process (pid: 495550).
[32m2025-07-03 00:25:02 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - 495550 - tune - STEP_START - Started execution of step "tune".
[32m2025-07-03 00:25:02 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - tune - Starting model tuning process
[32m2025-07-03 00:25:02 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - tune - Loading processed features and labels from database
/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/training.py:117: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  features_df = pl.DataFrame(features_result, schema=column_names)
[32m2025-07-03 00:25:02 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - tune - Loaded 1000 feature records
/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/training.py:136: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  labels_df = pl.DataFrame(labels_result, schema=labels_column_names)
[32m2025-07-03 00:25:02 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - tune - Using 51 features for training
[32m2025-07-03 00:25:02 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - tune - Dataset shape: (1000, 51), Target distribution: [932  68]
[32m2025-07-03 00:25:02 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - tune - Train set: (800, 51), Test set: (200, 51)
[32m2025-07-03 00:25:02 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - tune - Starting hyperparameter tuning with Optuna
[32m[I 2025-07-03 00:25:03,167][0m A new study created in RDB with name: random_forest_optimization_retrain_20250703_002502[0m
/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/sklearn/model_selection/_split.py:883: UserWarning: The groups parameter is ignored by StratifiedKFold
  warnings.warn(
[33m[W 2025-07-03 00:25:03,253][0m Trial 0 failed with parameters: {'n_estimators': 770, 'max_depth': 8, 'min_samples_split': 11, 'min_samples_leaf': 10, 'min_weight_fraction_leaf': 0.45483627584437136, 'max_features': 'sqrt', 'max_samples': 0.3324968682733033, 'max_leaf_nodes': 294, 'class_weight': 'balanced'} because of the following error: TypeError('Input should have at least 1 dimension i.e. satisfy `len(x.shape) > 0`, got scalar `array(5)` instead.').[0m
Traceback (most recent call last):
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/training.py", line 189, in <lambda>
    lambda trial: random_forest_objective(trial, X_train, y_train, skf),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/training.py", line 64, in random_forest_objective
    for train_idx, valid_idx in skf.split(X, y, n_splits):
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/sklearn/model_selection/_split.py", line 401, in split
    X, y, groups = indexable(X, y, groups)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/sklearn/utils/validation.py", line 530, in indexable
    check_consistent_length(*result)
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/sklearn/utils/validation.py", line 471, in check_consistent_length
    lengths = [_num_samples(X) for X in arrays if X is not None]
               ^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/sklearn/utils/validation.py", line 399, in _num_samples
    raise TypeError(
TypeError: Input should have at least 1 dimension i.e. satisfy `len(x.shape) > 0`, got scalar `array(5)` instead.
[33m[W 2025-07-03 00:25:03,255][0m Trial 0 failed with value None.[0m
[32m2025-07-03 00:25:03 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 4d0e9a3c-2417-49e6-accb-f1a4321a78ea - 495550 - tune - STEP_FAILURE - Execution of step "tune" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "tune"::

TypeError: Input should have at least 1 dimension i.e. satisfy `len(x.shape) > 0`, got scalar `array(5)` instead.

Stack Trace:
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/training.py", line 188, in tune
    study.optimize(
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/optuna/study/study.py", line 489, in optimize
    _optimize(
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/optuna/study/_optimize.py", line 64, in _optimize
    _optimize_sequential(
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/optuna/study/_optimize.py", line 161, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/optuna/study/_optimize.py", line 253, in _run_trial
    raise func_err
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/training.py", line 189, in <lambda>
    lambda trial: random_forest_objective(trial, X_train, y_train, skf),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/training.py", line 64, in random_forest_objective
    for train_idx, valid_idx in skf.split(X, y, n_splits):
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/sklearn/model_selection/_split.py", line 401, in split
    X, y, groups = indexable(X, y, groups)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/sklearn/utils/validation.py", line 530, in indexable
    check_consistent_length(*result)
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/sklearn/utils/validation.py", line 471, in check_consistent_length
    lengths = [_num_samples(X) for X in arrays if X is not None]
               ^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/sklearn/utils/validation.py", line 399, in _num_samples
    raise TypeError(
[0m
