[32m2025-07-02 23:05:24 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2c671dd8-ce08-4f84-a88d-42acd022d182 - 247245 - LOGS_CAPTURED - Started capturing logs in process (pid: 247245).
[32m2025-07-02 23:05:24 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 2c671dd8-ce08-4f84-a88d-42acd022d182 - 247245 - current_model - STEP_START - Started execution of step "current_model".
[32m2025-07-02 23:05:24 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 2c671dd8-ce08-4f84-a88d-42acd022d182 - current_model - Loading current deployed model from model registry
[32m2025-07-02 23:05:24 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 2c671dd8-ce08-4f84-a88d-42acd022d182 - current_model - Empty DataFrame
Columns: [name]
Index: []
[32m2025-07-02 23:05:24 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 2c671dd8-ce08-4f84-a88d-42acd022d182 - 247245 - current_model - STEP_FAILURE - Execution of step "current_model" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "current_model"::

duckdb.duckdb.CatalogException: Catalog Error: Table with name model_registry does not exist!
Did you mean "pg_indexes"?

LINE 3:             FROM model_registry
                         ^

Stack Trace:
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/predict.py", line 45, in current_model
    result = conn.execute(current_model_query).fetchone()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0m
