[32m2025-07-02 17:32:45 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0f7742e6-7fe1-4cb2-b918-cbfb5d6ccb61 - 26491 - LOGS_CAPTURED - Started capturing logs in process (pid: 26491).
[32m2025-07-02 17:32:46 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0f7742e6-7fe1-4cb2-b918-cbfb5d6ccb61 - 26491 - labels_ingestion - STEP_START - Started execution of step "labels_ingestion".
[32m2025-07-02 17:32:46 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0f7742e6-7fe1-4cb2-b918-cbfb5d6ccb61 - labels_ingestion - Loading file from: /workspaces/data-scientist-at-magenta/dagster_home/storage/core_data using PickledObjectFilesystemIOManager...
[32m2025-07-02 17:32:46 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0f7742e6-7fe1-4cb2-b918-cbfb5d6ccb61 - 26491 - labels_ingestion - LOADED_INPUT - Loaded input "core_data" using input manager "io_manager", from output "core_data" of step "core_data"
[32m2025-07-02 17:32:46 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 0f7742e6-7fe1-4cb2-b918-cbfb5d6ccb61 - 26491 - labels_ingestion - STEP_INPUT - Got input "core_data" of type "Any". (Type check passed).
[32m2025-07-02 17:32:46 +0000[0m - dagster - [34mINFO[0m - __ASSET_JOB - 0f7742e6-7fe1-4cb2-b918-cbfb5d6ccb61 - labels_ingestion - Starting labels ingestion
[32m2025-07-02 17:34:28 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 0f7742e6-7fe1-4cb2-b918-cbfb5d6ccb61 - 26491 - labels_ingestion - STEP_FAILURE - Execution of step "labels_ingestion" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "labels_ingestion"::

duckdb.duckdb.IOException: IO Error: Cannot open file "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/magenta_interview/dwh/database.duckdb": No such file or directory

Stack Trace:
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/src/code_location_interview/code_location_interview/assets/data_ingestion.py", line 158, in labels_ingestion
    with database.get_connection() as conn:
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster_duckdb/resource.py", line 62, in get_connection
    conn = backoff(
           ^^^^^^^^
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/backoff.py", line 71, in backoff
    raise to_raise
  File "/workspaces/data-scientist-at-magenta/.pixi/envs/ci-validation/lib/python3.12/site-packages/dagster/_utils/backoff.py", line 65, in backoff
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
[0m
